import React, { useState } from 'react';
import { Info, X } from 'lucide-react';

export default function IntegrityBanner() {
  const [dismissed, setDismissed] = useState(false);

  if (dismissed) return null;

  return (
    <aside aria-label="Dataset Provenance Disclaimer" className="integrity-banner">
      <Info size={15} color="var(--color-purple-dark)" style={{ flexShrink: 0 }} />
      <span>
        <strong>Dataset Provenance & Transparency Notice:</strong> Housing and demographic data are based on 1990 U.S. Census California block-group records. Property value estimates are generated by our trained machine-learning model. These are historical/statistical estimates for decision support and do not represent live MLS real-estate listings.
      </span>
      <button 
        onClick={() => setDismissed(true)} 
        style={{
          border: 'none',
          background: 'none',
          cursor: 'pointer',
          padding: '2px',
          color: 'var(--text-muted)',
          display: 'flex',
          alignItems: 'center',
          marginLeft: '8px'
        }}
        aria-label="Dismiss notice"
      >
        <X size={14} />
      </button>
    </aside>
  );
}
